"""initial schema

Revision ID: 18914404e412
Revises: 
Create Date: 2026-07-16 09:47:07.016190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18914404e412'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('hospital_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('genotype', sa.String(length=10), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('bed', sa.String(length=50), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=300), nullable=True),
    sa.Column('allergies', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_hospital_number'), ['hospital_number'], unique=False)

    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subspecialty', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('operating_days', sa.String(length=30), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=False),
    sa.Column('close_time', sa.String(length=5), nullable=False),
    sa.Column('break_start', sa.String(length=5), nullable=True),
    sa.Column('break_end', sa.String(length=5), nullable=True),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('load_balancing', sa.Enum('LEAST_BUSY', 'ROUND_ROBIN', name='loadbalancing'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consultation_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('station_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('station_type', sa.Enum('CONSULTANT', 'REGISTRAR', 'MEDICAL_OFFICER', 'RESIDENT', 'NURSE_PRACTITIONER', 'DIETICIAN', 'PHYSIOTHERAPY', 'PSYCHOLOGY', 'OCCUPATIONAL_THERAPY', 'SOCIAL_WELFARE', 'TELEMEDICINE', 'PROCEDURE', 'REVIEW', 'EMERGENCY_WALK_IN', name='stationtype'), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('max_patients', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='stationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_stations_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=True),
    sa.Column('target_department_id', sa.Integer(), nullable=True),
    sa.Column('target_specialty', sa.String(length=150), nullable=True),
    sa.Column('target_consultant', sa.String(length=150), nullable=True),
    sa.Column('consultation_type', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', 'ICU', 'WARD', 'CLINIC', 'EMERGENCY_DEPARTMENT', 'THEATRE', 'PREOPERATIVE', 'POSTOPERATIVE', 'NUTRITION', 'PAIN_MANAGEMENT', 'REHABILITATION', 'PSYCHOLOGICAL', 'SOCIAL_WELFARE', 'TELECONSULTATION', 'SECOND_OPINION', 'TUMOR_BOARD', 'MDT', 'REFERRAL', 'HOME_CARE', 'PALLIATIVE_CARE', 'DISCHARGE_PLANNING', name='consultationtype'), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', 'VIEWED', 'ACKNOWLEDGED', 'ACCEPTED', 'SEEN', 'TRANSFERRED', 'DELEGATED', 'REJECTED', 'RETURNED', 'ESCALATED', 'COMPLETED', 'CANCELLED', name='consultationstatus'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('specific_questions', sa.Text(), nullable=True),
    sa.Column('required_response_minutes', sa.Integer(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultations_status'), ['status'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('appointment_number', sa.String(length=40), nullable=True),
    sa.Column('appointment_type', sa.Enum('NEW_PATIENT', 'REVIEW', 'FOLLOW_UP', 'POSTOPERATIVE', 'PROCEDURE', 'TELEMEDICINE', 'EMERGENCY', 'WALK_IN', 'PRIORITY', 'VIP', 'STAFF', 'INSURANCE', 'PRIVATE', name='appointmenttype'), nullable=False),
    sa.Column('slot_start', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CONFIRMED', 'CHECKED_IN', 'WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'DID_NOT_ATTEND', 'CANCELLED', 'RESCHEDULED', 'REFERRED', 'ADMITTED', 'DISCHARGED', name='appointmentstatus'), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=300), nullable=True),
    sa.Column('rescheduled_to_id', sa.Integer(), nullable=True),
    sa.Column('booked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_to_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['consultation_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appointment_number'), ['appointment_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_slot_start'), ['slot_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index('uq_station_slot_active', ['station_id', 'slot_start'], unique=True, sqlite_where=sa.text("status NOT IN ('CANCELLED', 'RESCHEDULED')"), postgresql_where=sa.text("status NOT IN ('CANCELLED', 'RESCHEDULED')"))

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=120), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_consultation_id'), ['consultation_id'], unique=False)

    op.create_table('consultation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', 'VIEWED', 'ACKNOWLEDGED', 'ACCEPTED', 'SEEN', 'TRANSFERRED', 'DELEGATED', 'REJECTED', 'RETURNED', 'ESCALATED', 'COMPLETED', 'CANCELLED', name='consultationstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', 'VIEWED', 'ACKNOWLEDGED', 'ACCEPTED', 'SEEN', 'TRANSFERRED', 'DELEGATED', 'REJECTED', 'RETURNED', 'ESCALATED', 'COMPLETED', 'CANCELLED', name='consultationstatus'), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_events_consultation_id'), ['consultation_id'], unique=False)

    op.create_table('consultation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_messages_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultation_messages_created_at'), ['created_at'], unique=False)

    op.create_table('escalation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('notify_role', sa.String(length=50), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalation_events_consultation_id'), ['consultation_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('slot_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(), nullable=False),
    sa.Column('held_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['held_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['consultation_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slot_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_holds_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_holds_slot_start'), ['slot_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_holds_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slot_holds_station_id'))
        batch_op.drop_index(batch_op.f('ix_slot_holds_slot_start'))
        batch_op.drop_index(batch_op.f('ix_slot_holds_expires_at'))

    op.drop_table('slot_holds')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_consultation_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('escalation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalation_events_consultation_id'))

    op.drop_table('escalation_events')
    with op.batch_alter_table('consultation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_consultation_messages_consultation_id'))

    op.drop_table('consultation_messages')
    with op.batch_alter_table('consultation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_events_consultation_id'))

    op.drop_table('consultation_events')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_consultation_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('uq_station_slot_active', sqlite_where=sa.text("status NOT IN ('CANCELLED', 'RESCHEDULED')"), postgresql_where=sa.text("status NOT IN ('CANCELLED', 'RESCHEDULED')"))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_station_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_slot_start'))
        batch_op.drop_index(batch_op.f('ix_appointments_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_number'))

    op.drop_table('appointments')
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_status'))

    op.drop_table('consultations')
    with op.batch_alter_table('consultation_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_stations_clinic_id'))

    op.drop_table('consultation_stations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('clinics')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_hospital_number'))
        batch_op.drop_index(batch_op.f('ix_patients_full_name'))

    op.drop_table('patients')
    op.drop_table('departments')
    op.drop_table('institutions')
    # ### end Alembic commands ###
