"""waiting list, reminders, check-in code

Revision ID: 2a32d3f6a2a5
Revises: 18914404e412
Create Date: 2026-07-17 10:40:04.591852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a32d3f6a2a5'
down_revision: Union[str, Sequence[str], None] = '18914404e412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('offset_label', sa.String(length=10), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_reminders_appointment_id'), ['appointment_id'], unique=False)

    op.create_table('waiting_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('appointment_type', sa.Enum('NEW_PATIENT', 'REVIEW', 'FOLLOW_UP', 'POSTOPERATIVE', 'PROCEDURE', 'TELEMEDICINE', 'EMERGENCY', 'WALK_IN', 'PRIORITY', 'VIP', 'STAFF', 'INSURANCE', 'PRIVATE', name='appointmenttype'), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PROMOTED', 'CANCELLED', name='waitingstatus'), nullable=False),
    sa.Column('promoted_appointment_id', sa.Integer(), nullable=True),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['promoted_appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waiting_list_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiting_list_entries_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiting_list_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiting_list_entries_target_date'), ['target_date'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_code', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_check_in_code'), ['check_in_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_check_in_code'))
        batch_op.drop_column('check_in_code')

    with op.batch_alter_table('waiting_list_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiting_list_entries_target_date'))
        batch_op.drop_index(batch_op.f('ix_waiting_list_entries_status'))
        batch_op.drop_index(batch_op.f('ix_waiting_list_entries_clinic_id'))

    op.drop_table('waiting_list_entries')
    with op.batch_alter_table('appointment_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_reminders_appointment_id'))

    op.drop_table('appointment_reminders')
    # ### end Alembic commands ###
