"""user appearance + institution branding

Revision ID: 8579324800c5
Revises: 0dfca0c006b7
Create Date: 2026-07-17 22:09:44.901180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8579324800c5'
down_revision: Union[str, Sequence[str], None] = '0dfca0c006b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motto', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('logo_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('watermark_key', sa.String(length=120), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), server_default='system', nullable=False))
        batch_op.add_column(sa.Column('accent', sa.String(length=20), server_default='blue', nullable=False))
        batch_op.add_column(sa.Column('font_family', sa.String(length=20), server_default='system', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('font_family')
        batch_op.drop_column('accent')
        batch_op.drop_column('theme')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('watermark_key')
        batch_op.drop_column('logo_key')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('motto')

    # ### end Alembic commands ###
